// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/rs/xlog (interfaces: Logger)

// nolint
package logevent

import (
	gomock "github.com/golang/mock/gomock"
	xlog "github.com/rs/xlog"
)

// Mock of Logger interface
type mockLogger struct {
	ctrl     *gomock.Controller
	recorder *_mockLoggerRecorder
}

// Recorder for mockLogger (not exported)
type _mockLoggerRecorder struct {
	mock *mockLogger
}

func newMockLogger(ctrl *gomock.Controller) *mockLogger {
	mock := &mockLogger{ctrl: ctrl}
	mock.recorder = &_mockLoggerRecorder{mock}
	return mock
}

func (_m *mockLogger) EXPECT() *_mockLoggerRecorder {
	return _m.recorder
}

func (_m *mockLogger) Debug(_param0 ...interface{}) {
	_s := []interface{}{}
	for _, _x := range _param0 {
		_s = append(_s, _x)
	}
	_m.ctrl.Call(_m, "Debug", _s...)
}

func (_mr *_mockLoggerRecorder) Debug(arg0 ...interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Debug", arg0...)
}

func (_m *mockLogger) Debugf(_param0 string, _param1 ...interface{}) {
	_s := []interface{}{_param0}
	for _, _x := range _param1 {
		_s = append(_s, _x)
	}
	_m.ctrl.Call(_m, "Debugf", _s...)
}

func (_mr *_mockLoggerRecorder) Debugf(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	_s := append([]interface{}{arg0}, arg1...)
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Debugf", _s...)
}

func (_m *mockLogger) Error(_param0 ...interface{}) {
	_s := []interface{}{}
	for _, _x := range _param0 {
		_s = append(_s, _x)
	}
	_m.ctrl.Call(_m, "Error", _s...)
}

func (_mr *_mockLoggerRecorder) Error(arg0 ...interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Error", arg0...)
}

func (_m *mockLogger) Errorf(_param0 string, _param1 ...interface{}) {
	_s := []interface{}{_param0}
	for _, _x := range _param1 {
		_s = append(_s, _x)
	}
	_m.ctrl.Call(_m, "Errorf", _s...)
}

func (_mr *_mockLoggerRecorder) Errorf(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	_s := append([]interface{}{arg0}, arg1...)
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Errorf", _s...)
}

func (_m *mockLogger) Fatal(_param0 ...interface{}) {
	_s := []interface{}{}
	for _, _x := range _param0 {
		_s = append(_s, _x)
	}
	_m.ctrl.Call(_m, "Fatal", _s...)
}

func (_mr *_mockLoggerRecorder) Fatal(arg0 ...interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Fatal", arg0...)
}

func (_m *mockLogger) Fatalf(_param0 string, _param1 ...interface{}) {
	_s := []interface{}{_param0}
	for _, _x := range _param1 {
		_s = append(_s, _x)
	}
	_m.ctrl.Call(_m, "Fatalf", _s...)
}

func (_mr *_mockLoggerRecorder) Fatalf(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	_s := append([]interface{}{arg0}, arg1...)
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Fatalf", _s...)
}

func (_m *mockLogger) GetFields() xlog.F {
	ret := _m.ctrl.Call(_m, "GetFields")
	ret0, _ := ret[0].(xlog.F)
	return ret0
}

func (_mr *_mockLoggerRecorder) GetFields() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetFields")
}

func (_m *mockLogger) Info(_param0 ...interface{}) {
	_s := []interface{}{}
	for _, _x := range _param0 {
		_s = append(_s, _x)
	}
	_m.ctrl.Call(_m, "Info", _s...)
}

func (_mr *_mockLoggerRecorder) Info(arg0 ...interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Info", arg0...)
}

func (_m *mockLogger) Infof(_param0 string, _param1 ...interface{}) {
	_s := []interface{}{_param0}
	for _, _x := range _param1 {
		_s = append(_s, _x)
	}
	_m.ctrl.Call(_m, "Infof", _s...)
}

func (_mr *_mockLoggerRecorder) Infof(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	_s := append([]interface{}{arg0}, arg1...)
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Infof", _s...)
}

func (_m *mockLogger) Output(_param0 int, _param1 string) error {
	ret := _m.ctrl.Call(_m, "Output", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_mockLoggerRecorder) Output(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Output", arg0, arg1)
}

func (_m *mockLogger) OutputF(_param0 xlog.Level, _param1 int, _param2 string, _param3 map[string]interface{}) {
	_m.ctrl.Call(_m, "OutputF", _param0, _param1, _param2, _param3)
}

func (_mr *_mockLoggerRecorder) OutputF(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "OutputF", arg0, arg1, arg2, arg3)
}

func (_m *mockLogger) SetField(_param0 string, _param1 interface{}) {
	_m.ctrl.Call(_m, "SetField", _param0, _param1)
}

func (_mr *_mockLoggerRecorder) SetField(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetField", arg0, arg1)
}

func (_m *mockLogger) Warn(_param0 ...interface{}) {
	_s := []interface{}{}
	for _, _x := range _param0 {
		_s = append(_s, _x)
	}
	_m.ctrl.Call(_m, "Warn", _s...)
}

func (_mr *_mockLoggerRecorder) Warn(arg0 ...interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Warn", arg0...)
}

func (_m *mockLogger) Warnf(_param0 string, _param1 ...interface{}) {
	_s := []interface{}{_param0}
	for _, _x := range _param1 {
		_s = append(_s, _x)
	}
	_m.ctrl.Call(_m, "Warnf", _s...)
}

func (_mr *_mockLoggerRecorder) Warnf(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	_s := append([]interface{}{arg0}, arg1...)
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Warnf", _s...)
}

func (_m *mockLogger) Write(_param0 []byte) (int, error) {
	ret := _m.ctrl.Call(_m, "Write", _param0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_mockLoggerRecorder) Write(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Write", arg0)
}
